<a href="https://colab.research.google.com/github/ThanhTruc297PRJ/TH_DLN/blob/main/Bt_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**import thư viện **

In [2]:
import numpy as np

cách 1


In [3]:
# tạo list
my_list = [1, 9, 15, 39]

print("Python list:", my_list)

# chuyển list -> numpy array
my_numpy_array = np.array(my_list)

print("Numpy array:", my_numpy_array)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]


cách 2


In [4]:
a = np.array([1, 9, 15, 39])

print(a)

[ 1  9 15 39]


array 2 chiều

In [7]:
c = np.array([[1, 2, 3],
              [4, 5, 6]])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


array 3 chiều

In [8]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

print(d)
print(d.shape)
print(d.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
float64


Tạo array với giá trị ban đầu là 0 hoặc 1

In [9]:
e = np.zeros((2, 2))
f = np.ones((3, 3))

print("Zero matrix:\n", e)
print("One matrix:\n", f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Reshape thay đổi kích thước ma trận

In [10]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])

print(e)
print(e.shape)

f = e.reshape(3, 2)

print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

print(g)
print(g.shape)

h = g.reshape(3, 4)
print("reshape (3, 4)\n", h)

j = g.reshape(3, 2, 2)
print("reshape (3, 2, 2)\n", j)

k = g.reshape(2, 3, 2)
print("reshape (2, 3, 2)\n", k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


Flatten chuyển array nhiều chiều về 1 chiều

In [11]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])

f = e.flatten()

print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

j = g.flatten()

print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


Thêm dữ liệu bằng hstack và vstack

In [12]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print("Horizontal Append\n", h_stack)

v_stack = np.vstack((f, g))
print("Vertical Append\n", v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


Sinh mảng số nguyên ngẫu nhiên

In [13]:
a = np.random.randint(100, size=(5,))
print("Random 1-D array\n", a)

b = np.random.randint(100, size=(3, 4))
print("Random 2-D array\n", b)

c = np.random.randint(100, size=(3, 4, 3))
print("Random 3-D array\n", c)

Random 1-D array
 [41 31 66 29 64]
Random 2-D array
 [[77 37 29 80]
 [70 85  0 81]
 [98 49 24 33]]
Random 3-D array
 [[[73 27 89]
  [90 22 95]
  [22 70 28]
  [48 45 70]]

 [[98 76 98]
  [ 7 17 13]
  [68 63 80]
  [50 95 27]]

 [[32 99 43]
  [71 93  0]
  [53 67 37]
  [72 65 76]]]


Sinh ngẫu nhiên mảng số thực [0, 1]

In [14]:
a = np.random.rand(5)
print("Random 1-D array\n", a)

b = np.random.rand(3, 4)
print("Random 2-D array\n", b)

c = np.random.rand(3, 4, 3)
print("Random 3-D array\n", c)

Random 1-D array
 [0.03280981 0.5551937  0.35502787 0.09841171 0.45672068]
Random 2-D array
 [[0.03467452 0.23313531 0.87520709 0.90277991]
 [0.82261252 0.28346976 0.08174253 0.61333193]
 [0.08969123 0.51284353 0.14943454 0.65003633]]
Random 3-D array
 [[[2.99151994e-01 8.65374842e-01 1.14473733e-01]
  [2.33538075e-01 3.28764187e-01 5.56678259e-01]
  [2.84062504e-01 1.92598639e-01 3.06949411e-01]
  [9.73021577e-01 1.83259310e-01 2.93131026e-01]]

 [[3.75816398e-02 3.49419322e-01 5.71779629e-01]
  [9.37474524e-01 8.60996218e-01 9.14242227e-01]
  [4.77297942e-02 8.43832113e-01 9.48835338e-01]
  [3.51770955e-01 6.12176386e-01 9.82150349e-01]]

 [[1.85073787e-01 4.08296777e-01 8.38072863e-01]
  [9.96643236e-01 4.40129584e-01 9.15669731e-01]
  [8.02941457e-01 1.46649027e-01 8.93431781e-01]
  [8.81191436e-01 5.44130526e-04 8.25038641e-01]]]


Sinh ngẫu nhiên Phân phối chuẩn Gaussian

In [15]:
a = np.random.normal(5, 0.5, 10)

print(a)

[5.36030039 4.97461963 5.11491112 4.70971095 5.66826531 4.5437796
 4.9583896  5.5262672  5.44755219 4.83721601]


Sinh 1 giá trị ngẫu nhiên từ mảng cho trước


In [17]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

print(a)

4


Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước

In [18]:
b = np.random.choice(
    [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    size=(3, 5)
)

print(b)

[[ 2 12 20 18  4]
 [20 10  6 20 20]
 [ 4  4 10  6 14]]



Tạo ma trận 5 x 5 toàn số 1

In [19]:

A = np.matrix(np.ones((5, 5)))

print("The matrix\n", A)

# Đổi dòng thứ 3 thành số 2

np.array(A)[2] = 2

print("Change values of third row with array\n", A)

np.asarray(A)[2] = 2

print("Change values of third row with asarray\n", A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Dùng arange

In [20]:
# tạo số nguyên từ 1 -> 19
a = np.arange(1, 20)

print(a)

# bước nhảy 2
b = np.arange(1, 20, 2)

print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


Dùng linspace

In [21]:
a = np.linspace(1., 5., num=10)

print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Index và slice

In [22]:
# slice

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)

print("first row:", a[0])

print("second row:", a[1])

# indexing
print("Second column:", a[:,1])

print("first column", a[:,0])

print("First two values of second row:", a[1,:2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]
