<a href="https://colab.research.google.com/github/ThanhTruc297PRJ/TH_DLN/blob/main/Bt_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**import thư viện **

In [ ]:
import numpy as np

cách 1


In [ ]:
# tạo list
my_list = [1, 9, 15, 39]

print("Python list:", my_list)

# chuyển list -> numpy array
my_numpy_array = np.array(my_list)

print("Numpy array:", my_numpy_array)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]


cách 2


In [ ]:
a = np.array([1, 9, 15, 39])

print(a)

[ 1  9 15 39]


array 2 chiều

In [ ]:
c = np.array([[1, 2, 3],
              [4, 5, 6]])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


array 3 chiều

In [ ]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

print(d)
print(d.shape)
print(d.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
float64


Tạo array với giá trị ban đầu là 0 hoặc 1

In [ ]:
e = np.zeros((2, 2))
f = np.ones((3, 3))

print("Zero matrix:\n", e)
print("One matrix:\n", f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Reshape thay đổi kích thước ma trận

In [ ]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])

print(e)
print(e.shape)

f = e.reshape(3, 2)

print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

print(g)
print(g.shape)

h = g.reshape(3, 4)
print("reshape (3, 4)\n", h)

j = g.reshape(3, 2, 2)
print("reshape (3, 2, 2)\n", j)

k = g.reshape(2, 3, 2)
print("reshape (2, 3, 2)\n", k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


Flatten chuyển array nhiều chiều về 1 chiều

In [ ]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])

f = e.flatten()

print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

j = g.flatten()

print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


Thêm dữ liệu bằng hstack và vstack

In [ ]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print("Horizontal Append\n", h_stack)

v_stack = np.vstack((f, g))
print("Vertical Append\n", v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


Sinh mảng số nguyên ngẫu nhiên

In [ ]:
a = np.random.randint(100, size=(5,))
print("Random 1-D array\n", a)

b = np.random.randint(100, size=(3, 4))
print("Random 2-D array\n", b)

c = np.random.randint(100, size=(3, 4, 3))
print("Random 3-D array\n", c)

Random 1-D array
 [41 31 66 29 64]
Random 2-D array
 [[77 37 29 80]
 [70 85  0 81]
 [98 49 24 33]]
Random 3-D array
 [[[73 27 89]
  [90 22 95]
  [22 70 28]
  [48 45 70]]

 [[98 76 98]
  [ 7 17 13]
  [68 63 80]
  [50 95 27]]

 [[32 99 43]
  [71 93  0]
  [53 67 37]
  [72 65 76]]]


Sinh ngẫu nhiên mảng số thực [0, 1]

In [ ]:
a = np.random.rand(5)
print("Random 1-D array\n", a)

b = np.random.rand(3, 4)
print("Random 2-D array\n", b)

c = np.random.rand(3, 4, 3)
print("Random 3-D array\n", c)

Random 1-D array
 [0.03280981 0.5551937  0.35502787 0.09841171 0.45672068]
Random 2-D array
 [[0.03467452 0.23313531 0.87520709 0.90277991]
 [0.82261252 0.28346976 0.08174253 0.61333193]
 [0.08969123 0.51284353 0.14943454 0.65003633]]
Random 3-D array
 [[[2.99151994e-01 8.65374842e-01 1.14473733e-01]
  [2.33538075e-01 3.28764187e-01 5.56678259e-01]
  [2.84062504e-01 1.92598639e-01 3.06949411e-01]
  [9.73021577e-01 1.83259310e-01 2.93131026e-01]]

 [[3.75816398e-02 3.49419322e-01 5.71779629e-01]
  [9.37474524e-01 8.60996218e-01 9.14242227e-01]
  [4.77297942e-02 8.43832113e-01 9.48835338e-01]
  [3.51770955e-01 6.12176386e-01 9.82150349e-01]]

 [[1.85073787e-01 4.08296777e-01 8.38072863e-01]
  [9.96643236e-01 4.40129584e-01 9.15669731e-01]
  [8.02941457e-01 1.46649027e-01 8.93431781e-01]
  [8.81191436e-01 5.44130526e-04 8.25038641e-01]]]


Sinh ngẫu nhiên Phân phối chuẩn Gaussian

In [ ]:
a = np.random.normal(5, 0.5, 10)

print(a)

[5.36030039 4.97461963 5.11491112 4.70971095 5.66826531 4.5437796
 4.9583896  5.5262672  5.44755219 4.83721601]


Sinh 1 giá trị ngẫu nhiên từ mảng cho trước


In [ ]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

print(a)

4


Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước

In [ ]:
b = np.random.choice(
    [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    size=(3, 5)
)

print(b)

[[ 2 12 20 18  4]
 [20 10  6 20 20]
 [ 4  4 10  6 14]]



Tạo ma trận 5 x 5 toàn số 1

In [ ]:

A = np.matrix(np.ones((5, 5)))

print("The matrix\n", A)

# Đổi dòng thứ 3 thành số 2

np.array(A)[2] = 2

print("Change values of third row with array\n", A)

np.asarray(A)[2] = 2

print("Change values of third row with asarray\n", A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Dùng arange

In [ ]:
# tạo số nguyên từ 1 -> 19
a = np.arange(1, 20)

print(a)

# bước nhảy 2
b = np.arange(1, 20, 2)

print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


Dùng linspace

In [ ]:
a = np.linspace(1., 5., num=10)

print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Index và slice

In [ ]:
# slice

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)

print("first row:", a[0])

print("second row:", a[1])

# indexing
print("Second column:", a[:,1])

print("first column", a[:,0])

print("First two values of second row:", a[1,:2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


Cài đặt pandas

In [1]:
pip install pandas


series cấu trúc dữ liệu 1 chiều

In [2]:
import pandas as pd

# Tao pandas series tu list
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])

# Tao pandas series tu dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


tạo đối tượng dataframe

In [3]:
import numpy as np
import pandas as pd

# Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)

# Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy array:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


tạo dataframe mảng 2 chieuf có tên cột

In [4]:
import pandas as pd

# Tạo DataFrame mảng 2-chiều có tên cột
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [5]:
import numpy as np
import pandas as pd

# tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  # in 5 dòng đầu tiên

        so1       so2       so3       so4
0 -0.202121  0.702179 -0.283761 -0.689639
1 -0.116662 -0.179538 -2.154772  1.562309
2 -1.782144  0.309343  0.184919  0.495748
3 -0.306072  0.299925  0.361143 -0.612987
4  1.810743  0.666485 -1.389075  0.661834


In [6]:
import numpy as np
import pandas as pd

# tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  # in 5 dòng đầu tiên

# chọn 1 cột
print('Chọn cột so1\n', df['so1'])

# chọn nhiều dòng
print('Chọn nhiều dòng\n', df[0:3])

# chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])

# chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

# Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0  1.591602  2.016449  0.934835  1.080836
1  2.141808  0.107008  0.432587  0.308852
2 -0.158905 -0.489642  0.243187  1.173604
3  0.503694 -1.402495  1.117439 -0.742666
4  1.709258 -0.448170  1.565560  0.981115
Chọn cột so1
 0     1.591602
1     2.141808
2    -0.158905
3     0.503694
4     1.709258
5     1.063226
6    -0.345266
7    -0.808245
8     0.108727
9     0.008261
10    0.707757
11    0.581999
12    0.160989
13   -1.768232
14   -0.557794
15   -1.748350
16   -1.428246
17   -0.332416
18   -0.749007
19    0.157577
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  1.591602  2.016449  0.934835  1.080836
1  2.141808  0.107008  0.432587  0.308852
2 -0.158905 -0.489642  0.243187  1.173604
Chọn nhiều cột
          so1       so3
0   1.591602  0.934835
1   2.141808  0.432587
2  -0.158905  0.243187
3   0.503694  1.117439
4   1.709258  1.565560
5   1.063226 -2.324866
6  -0.345266 -0.744077
7  -0.808245 -0.504527


In [7]:
import pandas as pd

# Đọc dữ liệu từ CSV
path = '/content/sample_data/Salary_Data.csv'

COLUMNS = ['YearsExperience', 'Salary']

df_csv = pd.read_csv(
    path,
    skipinitialspace=True,
    names=COLUMNS,
    index_col=False
)

print(df_csv.head())
print(df_csv.shape)

df_csv1 = pd.read_csv(
    path,
    skipinitialspace=True,
    index_col=False
)

print(df_csv1.head())
print(df_csv1.shape)

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/Salary_Data.csv'

In [9]:
import pandas as pd

# Gom nhóm dữ liệu trong DataFrame
path = '/content/sample_data/Fish.csv'

df_csv = pd.read_csv(
    path,
    skipinitialspace=True,
    index_col=False
)

print(df_csv.head())

print(df_csv.groupby(['Species']).mean().head())

print(df_csv.groupby(['Species'])['Weight'].min().head())

print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/Fish.csv'

**BÀI TẬP**

In [10]:
import numpy as np
import pandas as pd

Bài 1 Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 x 3, giá trị [0, 20]. Kiểm tra có phần tử khác 0 hay không.

In [11]:
import numpy as np

arr = np.random.randint(0, 21, size=(3, 3, 3))

print("Mảng 3 x 3 x 3:")
print(arr)

kiem_tra = np.any(arr != 0)

print("Có phần tử khác 0 không?", kiem_tra)

Mảng 3 x 3 x 3:
[[[14 14  1]
  [ 0 20 11]
  [ 6 15 13]]

 [[17  3 13]
  [ 5 19  2]
  [10 11  9]]

 [[ 2 13  3]
  [12  0 11]
  [ 7  6 18]]]
Có phần tử khác 0 không? True


Bài 2

Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 x 3, giá trị [0, 20]. Kiểm tra toàn bộ phần tử có khác 0 hay không.

In [12]:
import numpy as np

arr = np.random.randint(0, 21, size=(3, 3, 3))

print("Mảng 3 x 3 x 3:")
print(arr)

kiem_tra = np.all(arr != 0)

print("Tất cả phần tử đều khác 0 không?", kiem_tra)

Mảng 3 x 3 x 3:
[[[ 2  2 16]
  [12  3 16]
  [12  6 13]]

 [[ 8  4 12]
  [15 10 11]
  [13  2  3]]

 [[ 5 19 14]
  [18  3  9]
  [ 7  4  3]]]
Tất cả phần tử đều khác 0 không? True


Bài 3

So sánh 2 mảng 1 chiều, 2 chiều bằng các hàm greater, greater_equal, less, less_equal.

In [13]:
import numpy as np

# So sánh mảng 1 chiều
a = np.array([1, 5, 8, 10])
b = np.array([2, 5, 6, 12])

print("Mảng 1 chiều a:", a)
print("Mảng 1 chiều b:", b)

print("a > b:", np.greater(a, b))
print("a >= b:", np.greater_equal(a, b))
print("a < b:", np.less(a, b))
print("a <= b:", np.less_equal(a, b))

print("\n----------------------\n")

# So sánh mảng 2 chiều
x = np.array([[1, 5], [8, 10]])
y = np.array([[2, 5], [6, 12]])

print("Mảng 2 chiều x:")
print(x)

print("Mảng 2 chiều y:")
print(y)

print("x > y:")
print(np.greater(x, y))

print("x >= y:")
print(np.greater_equal(x, y))

print("x < y:")
print(np.less(x, y))

print("x <= y:")
print(np.less_equal(x, y))

Mảng 1 chiều a: [ 1  5  8 10]
Mảng 1 chiều b: [ 2  5  6 12]
a > b: [False False  True False]
a >= b: [False  True  True False]
a < b: [ True False False  True]
a <= b: [ True  True False  True]

----------------------

Mảng 2 chiều x:
[[ 1  5]
 [ 8 10]]
Mảng 2 chiều y:
[[ 2  5]
 [ 6 12]]
x > y:
[[False False]
 [ True False]]
x >= y:
[[False  True]
 [ True False]]
x < y:
[[ True False]
 [False  True]]
x <= y:
[[ True  True]
 [False  True]]


Bài 4

Tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5.

In [14]:
import numpy as np

arr = np.concatenate([
    np.ones(10),
    np.zeros(10),
    np.full(10, 5)
])

print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


Bài 5

Tạo mảng số nguyên chẵn từ [30, 70].

In [15]:
import numpy as np

arr = np.arange(30, 71, 2)

print("Các số chẵn từ 30 đến 70:")
print(arr)

Các số chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Bài 6

Tạo ma trận đơn vị 3 x 3.

In [16]:
import numpy as np

arr = np.identity(3)

print("Ma trận đơn vị 3 x 3:")
print(arr)

Ma trận đơn vị 3 x 3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Bài 7

Tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoại trừ phần tử đầu và cuối.

In [17]:
import numpy as np

arr = np.random.randint(15, 56, size=10)

print("Mảng ban đầu:")
print(arr)

print("Mảng bỏ phần tử đầu và cuối:")
print(arr[1:-1])

Mảng ban đầu:
[43 21 18 36 54 17 53 33 16 50]
Mảng bỏ phần tử đầu và cuối:
[21 18 36 54 17 53 33 16]


Bài 8

Tạo mảng 20 phần tử trong khoảng [0, 20], đổi dấu các số trong khoảng [9, 15].

In [18]:
import numpy as np

arr = np.random.randint(0, 21, size=20)

print("Mảng ban đầu:")
print(arr)

arr[(arr >= 9) & (arr <= 15)] *= -1

print("Mảng sau khi đổi dấu các số trong khoảng [9, 15]:")
print(arr)

Mảng ban đầu:
[20  0 18 13  5  2 16 10 19  4  3 14  9  3  6 20  7  3 20  2]
Mảng sau khi đổi dấu các số trong khoảng [9, 15]:
[ 20   0  18 -13   5   2  16 -10  19   4   3 -14  -9   3   6  20   7   3
  20   2]


Bài 9

Tạo ma trận 3 x 4, mỗi phần tử có giá trị từ [10, 21].

In [19]:
import numpy as np

arr = np.random.randint(10, 22, size=(3, 4))

print("Ma trận 3 x 4:")
print(arr)

Ma trận 3 x 4:
[[17 21 16 13]
 [14 16 19 17]
 [21 10 11 17]]


Bài 10

Tạo ma trận 10 x 10, biên là 1, bên trong là 0.

In [20]:
import numpy as np

arr = np.ones((10, 10))

arr[1:-1, 1:-1] = 0

print("Ma trận 10 x 10:")
print(arr)

Ma trận 10 x 10:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Bài 11

Tạo ma trận 5 x 5, đường chéo chính là 1, 2, 3, 4, 5.

In [21]:
import numpy as np

arr = np.diag([1, 2, 3, 4, 5])

print("Ma trận 5 x 5:")
print(arr)

Ma trận 5 x 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Bài 12

Tạo mảng 3 x 3 x 3, tính tổng theo mỗi dòng, mỗi cột.

In [22]:
import numpy as np

arr = np.random.randint(0, 10, size=(3, 3, 3))

print("Mảng 3 x 3 x 3:")
print(arr)

print("Tổng theo axis = 0:")
print(np.sum(arr, axis=0))

print("Tổng theo axis = 1:")
print(np.sum(arr, axis=1))

print("Tổng theo axis = 2:")
print(np.sum(arr, axis=2))

Mảng 3 x 3 x 3:
[[[1 6 4]
  [3 6 8]
  [4 1 2]]

 [[8 8 7]
  [1 5 4]
  [6 9 1]]

 [[1 3 7]
  [9 3 6]
  [8 7 1]]]
Tổng theo axis = 0:
[[10 17 18]
 [13 14 18]
 [18 17  4]]
Tổng theo axis = 1:
[[ 8 13 14]
 [15 22 12]
 [18 13 14]]
Tổng theo axis = 2:
[[11 17  7]
 [23 10 16]
 [11 18 16]]


Bài 13

Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product.

In [23]:
import numpy as np

a = np.random.randint(0, 10, size=10)
b = np.random.randint(0, 10, size=10)

print("Vector a:")
print(a)

print("Vector b:")
print(b)

ket_qua = np.dot(a, b)

print("Inner product của a và b:", ket_qua)

Vector a:
[1 2 6 3 4 3 6 4 8 7]
Vector b:
[7 5 0 3 9 8 5 9 5 2]
Inner product của a và b: 206


Bài 14

Tạo ma trận A = 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của ma trận A.

In [24]:
import numpy as np

A = np.random.randint(0, 10, size=(4, 3))
y = np.random.randint(0, 10, size=3)

print("Ma trận A:")
print(A)

print("Vector y:")
print(y)

ket_qua = A + y

print("Kết quả sau khi thêm vector y vào từng dòng của A:")
print(ket_qua)

Ma trận A:
[[4 7 0]
 [3 0 4]
 [1 9 5]
 [2 2 4]]
Vector y:
[7 0 6]
Kết quả sau khi thêm vector y vào từng dòng của A:
[[11  7  6]
 [10  0 10]
 [ 8  9 11]
 [ 9  2 10]]


Bài 15

Pandas cộng, trừ, nhân, chia 2 Series.

In [25]:
import pandas as pd

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:")
print(s1)

print("Series 2:")
print(s2)

print("Cộng:")
print(s1 + s2)

print("Trừ:")
print(s1 - s2)

print("Nhân:")
print(s1 * s2)

print("Chia:")
print(s1 / s2)

Series 1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series 2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Cộng:
0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


Bài 16

Chuyển cột đầu tiên thành Series.

In [26]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['John', 'Smith', 'Anna'],
    'Age': [30, 40, 25],
    'Score': [8.5, 7.0, 9.0]
})

print("DataFrame ban đầu:")
print(df)

series_dau_tien = df.iloc[:, 0]

print("Cột đầu tiên chuyển thành Series:")
print(series_dau_tien)

print("Kiểu dữ liệu:")
print(type(series_dau_tien))

DataFrame ban đầu:
    Name  Age  Score
0   John   30    8.5
1  Smith   40    7.0
2   Anna   25    9.0
Cột đầu tiên chuyển thành Series:
0     John
1    Smith
2     Anna
Name: Name, dtype: object
Kiểu dữ liệu:
<class 'pandas.core.series.Series'>


Bài 17

Viết chương trình Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên.

In [27]:
import pandas as pd
import numpy as np

# Tạo DataFrame 4 x 3 ngẫu nhiên
df = pd.DataFrame(
    np.random.randint(1, 100, size=(4, 3)),
    columns=['A', 'B', 'C']
)

print("DataFrame ban đầu:")
print(df)

# Sắp xếp theo cột A
df_sort_A = df.sort_values(by='A')

print("\nDataFrame sau khi sắp xếp theo cột A:")
print(df_sort_A)

# Sắp xếp theo cột B
df_sort_B = df.sort_values(by='B')

print("\nDataFrame sau khi sắp xếp theo cột B:")
print(df_sort_B)

# Sắp xếp theo cột C
df_sort_C = df.sort_values(by='C')

print("\nDataFrame sau khi sắp xếp theo cột C:")
print(df_sort_C)

DataFrame ban đầu:
    A   B   C
0  73  17  94
1  57  65  40
2  35  13  69
3  96   7  12

DataFrame sau khi sắp xếp theo cột A:
    A   B   C
2  35  13  69
1  57  65  40
0  73  17  94
3  96   7  12

DataFrame sau khi sắp xếp theo cột B:
    A   B   C
3  96   7  12
2  35  13  69
0  73  17  94
1  57  65  40

DataFrame sau khi sắp xếp theo cột C:
    A   B   C
3  96   7  12
1  57  65  40
2  35  13  69
0  73  17  94


Bài 18

Viết chương trình Pandas thay đổi index của một Series bằng reindex.

In [28]:
import pandas as pd

# Tạo Series ban đầu
s = pd.Series(
    [1, 2, 3, 4, 5],
    index=['A', 'B', 'C', 'D', 'E']
)

print("Original Data Series:")
print(s)

# Thay đổi thứ tự index
s_reindex = s.reindex(['B', 'A', 'C', 'D', 'E'])

print("\nData Series after changing the order of index:")
print(s_reindex)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64

Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


Bài 19

Tìm những phần tử trong Series x mà không có trong Series y.

In [29]:
import pandas as pd

sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("sr1:")
print(sr1)

print("\nsr2:")
print(sr2)

result = sr1[~sr1.isin(sr2)]

print("\nItems of sr1 not present in sr2:")
print(result)

sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64

sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2:
0    1
2    3
4    5
dtype: int64


Bài 21

Viết chương trình Pandas thêm Series y vào Series x theo chiều dọc và chiều ngang.

In [30]:
import pandas as pd

# Tạo Series x
x = pd.Series(range(10))

# Tạo Series y
y = pd.Series(list('pqrstuvwxy'))

print("Series x")
print(x)

print("\nSeries y")
print(y)

# Thêm series y vào series x theo chiều dọc
vertical = pd.concat([x, y], axis=0)

print("\nThêm series y vào series x theo chiều dọc vertical:")
print(vertical)

# Thêm series y vào series x theo chiều ngang
horizontal = pd.concat([x, y], axis=1)

print("\nThêm series y vào series x theo chiều ngang horizontal:")
print(horizontal)

Series x
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

Series y
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Thêm series y vào series x theo chiều dọc vertical:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Thêm series y vào series x theo chiều ngang horizontal:
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


Bài 22

Tạo và hiển thị DataFrame.

In [31]:
import pandas as pd
import numpy as np

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
             'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no',
                'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)

print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


Bài 23

Từ bài 22, cho biết 3 dòng đầu tiên.

In [32]:
print("3 dòng đầu tiên:")
print(df.head(3))

3 dòng đầu tiên:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


Bài 24

Từ bài 22, chọn cột name và score.

In [33]:
print("Cột name và score:")
print(df[['name', 'score']])

Cột name và score:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


Bài 25

Từ bài 22, chọn những dòng có attempts > 2.

In [34]:
print("Những dòng có attempts > 2:")
print(df[df['attempts'] > 2])

Những dòng có attempts > 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


Bài 26

Từ bài 22, cho biết số dòng, số cột của DataFrame.

In [35]:
print("Số dòng, số cột của DataFrame:")
print(df.shape)

print("Số dòng:", df.shape[0])
print("Số cột:", df.shape[1])

Số dòng, số cột của DataFrame:
(10, 4)
Số dòng: 10
Số cột: 4


Bài 27

Từ bài 22, cho biết những dòng có score là NaN.

In [36]:
print("Những dòng có score là NaN:")
print(df[df['score'].isnull()])

Những dòng có score là NaN:
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


Bài 28

Từ bài 22, cho biết những dòng có score trong khoảng (15, 20).

In [37]:
print("Những dòng có score trong khoảng (15, 20):")
print(df[df['score'].between(15, 20)])

Những dòng có score trong khoảng (15, 20):
        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


Bài 29

Từ bài 22, cho biết những dòng có attempts > 2 và score trong khoảng (15, 20).

In [38]:
print("Những dòng có attempts > 2 và score trong khoảng (15, 20):")
print(df[(df['attempts'] > 2) & (df['score'].between(15, 20))])

Những dòng có attempts > 2 và score trong khoảng (15, 20):
      name  score  attempts qualify
f  Michael   20.0         3     yes


Bài 30

Từ bài 22, thay đổi giá trị dòng d, cột score là 19.

In [39]:
df.loc['d', 'score'] = 19

print("DataFrame sau khi đổi score dòng d thành 19:")
print(df)

DataFrame sau khi đổi score dòng d thành 19:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
