<a href="https://colab.research.google.com/github/ThanhTruc297PRJ/TH_DLN/blob/main/tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensorflow**

Tensor 0-chiều

In [1]:
import tensorflow as tf

# This will be an int32 tensor by default
rank_0_tensor = tf.constant(4)

print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


Ví dụ thêm các kiểu dữ liệu int16, float32, string:

In [3]:
import tensorflow as tf

# Tensor scalar kiểu int16
tensor_int16 = tf.constant(4, dtype=tf.int16)
print("Tensor int16:")
print(tensor_int16)

# Tensor scalar kiểu float32
tensor_float32 = tf.constant(4.0, dtype=tf.float32)
print("\nTensor float32:")
print(tensor_float32)

# Tensor scalar kiểu string
tensor_string = tf.constant("Hello TensorFlow")
print("\nTensor string:")
print(tensor_string)

Tensor int16:
tf.Tensor(4, shape=(), dtype=int16)

Tensor float32:
tf.Tensor(4.0, shape=(), dtype=float32)

Tensor string:
tf.Tensor(b'Hello TensorFlow', shape=(), dtype=string)


Tensor 1-chiều

In [4]:
import tensorflow as tf

# We make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


Tensor 2-chiều Ma trận

In [5]:
import tensorflow as tf

rank_2_tensor = tf.constant(
    [[1, 2],
     [3, 4],
     [5, 6]],
    dtype=tf.float16
)

print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


Tensor n-chiều nhiều trục

In [6]:
import tensorflow as tf

rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


3.5. Thuộc tính của tensor

In [7]:
import tensorflow as tf

rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(rank_3_tensor)
print("shape:", rank_3_tensor.shape)
print("type of tensor:", rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


3.6. Tạo tensor tự động gán giá trị 0 ban đầu

In [8]:
import tensorflow as tf

t_zero = tf.zeros(10)
print(t_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [9]:
import tensorflow as tf

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [10]:
import tensorflow as tf

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


3.7. Tạo tensor tự động gán giá trị 1 ban đầu

In [11]:
import tensorflow as tf

t_one = tf.ones(10)
print(t_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)


In [12]:
import tensorflow as tf

t_2_one = tf.ones([3, 3])
print(t_2_one)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [13]:
import tensorflow as tf

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


3.8. Tạo tensor tự động với giá trị bất kỳ

In [14]:
import tensorflow as tf

t_1 = tf.fill([3], 10)
print(t_1)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [15]:
import tensorflow as tf

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


3.9. Tạo tensor 1-chiều với hàm linspace

In [16]:
import tensorflow as tf

lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


3.10. Tạo tensor 1-chiều với hàm range

In [17]:
import tensorflow as tf

range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [18]:
import tensorflow as tf

range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


3.11. Tạo tensor với giá trị ngẫu nhiên

tạo tensor ngẫu nhiên với hàm random.normal

In [19]:
import tensorflow as tf

range_tensor = tf.random.normal([5])
print(range_tensor)

tf.Tensor([-0.3135514   0.00785571  1.4889517  -0.22257964 -0.55139124], shape=(5,), dtype=float32)


In [20]:
import tensorflow as tf

range_tensor = tf.random.normal([3, 3])
print(range_tensor)

tf.Tensor(
[[ 0.52482605 -0.6028319   0.24183026]
 [-0.28636402 -0.10093621  0.7625193 ]
 [ 1.1317261  -1.5879241   0.60826516]], shape=(3, 3), dtype=float32)


tạo tensor ngẫu nhiên với hàm truncated_normal

In [21]:
import tensorflow as tf

range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

tf.Tensor([ 1.7102745  -0.38413432 -1.6713324   0.98830223 -1.752169  ], shape=(5,), dtype=float32)


In [22]:
import tensorflow as tf

range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

tf.Tensor(
[[ 0.4324666   0.57607526]
 [-0.4082442   0.5300528 ]
 [ 0.7932881  -1.200118  ]], shape=(3, 2), dtype=float32)


In [23]:
import tensorflow as tf

range_tensor = tf.random.truncated_normal([3, 2, 2])
print(range_tensor)

tf.Tensor(
[[[ 1.1938962  -0.43506864]
  [ 1.4997138  -0.26618123]]

 [[-0.792235   -0.23918527]
  [ 0.13068439  0.6435418 ]]

 [[-0.9485138   0.82887477]
  [ 1.2487799   0.34555173]]], shape=(3, 2, 2), dtype=float32)


tạo tensor ngẫu nhiên với hàm random.uniform

In [24]:
import tensorflow as tf

range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor([16.248455 13.230904 14.276484 12.007725 17.133486], shape=(5,), dtype=float32)


In [25]:
import tensorflow as tf

range_tensor = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor)

tf.Tensor(
[[14.617668 12.107998]
 [10.102957 13.744021]
 [15.352245 13.745319]], shape=(3, 2), dtype=float32)


In [26]:
import tensorflow as tf

range_tensor = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor(
[[[19.605392 15.071821 19.510498 17.33635  16.82336 ]
  [19.170853 10.421042 15.794859 17.464256 18.575428]]

 [[12.514866 11.3022   16.32029  15.709859 10.765316]
  [12.46352  14.393846 14.506758 17.075287 15.572957]]

 [[12.14518  18.566372 12.031604 10.414587 19.646147]
  [11.746637 14.564695 19.201653 19.277622 16.068535]]], shape=(3, 2, 5), dtype=float32)


tạo tensor ngẫu nhiên với hàm random.uniform và dùng shuffle để xáo trộn giá trị trong tensor

In [27]:
import tensorflow as tf

range_tensor = tf.random.uniform([5], minval=10, maxval=20)

print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([14.073672 11.865796 10.137209 10.927895 12.820157], shape=(5,), dtype=float32)
tf.Tensor([10.137209 11.865796 14.073672 10.927895 12.820157], shape=(5,), dtype=float32)
